name: CI

on:
  pull_request:
  push:
    branches: [ main ]

env:
  PYTHON_VERSION: "3.13.5"
  PIP_CACHE_DIR: ~/.cache/pip
  POETRY_CACHE_DIR: ~/.cache/pypoetry

jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: ${{ env.PYTHON_VERSION }} }

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ${{ env.PIP_CACHE_DIR }}
          key: pip-${{ runner.os }}-${{ env.PYTHON_VERSION }}-${{ hashFiles('pyproject.toml', 'poetry.lock', 'requirements.txt') }}

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f poetry.lock ]; then
            pip install poetry && poetry config virtualenvs.create false && poetry install -n
          elif [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install black ruff mypy

      - name: Lint (ruff)
        run: ruff check .
      - name: Format check (black)
        run: black --check .
      - name: Type check (mypy)
        run: mypy src || true  # 단계 도입 초기에 느슨히, 이후 강제 통과로 변경

  unit:
    runs-on: ubuntu-latest
    needs: [ precheck ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ env.PYTHON_VERSION }} }
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f poetry.lock ]; then
            pip install poetry && poetry config virtualenvs.create false && poetry install -n
          else
            pip install -r requirements.txt
          fi
          pip install pytest pytest-cov
      - name: Pytest (unit only)
        run: |
          pytest -q tests/unit --maxfail=1 --disable-warnings \
            --junitxml=tests/reports/pytest-unit.xml \
            --cov=src --cov-report=xml:tests/reports/coverage-unit.xml
      - name: Upload unit reports
        uses: actions/upload-artifact@v4
        with:
          name: unit-reports
          path: |
            tests/reports/pytest-unit.xml
            tests/reports/coverage-unit.xml

  integration:
    runs-on: ubuntu-latest
    needs: [ unit ]
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: 0000
          MYSQL_DATABASE: novels
        ports: [ "3306:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot || exit 1"
          --health-interval=10s --health-timeout=5s --health-retries=10
          --name novels-mysql
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_0900_ai_ci
      mongo:
        image: mongo:7
        ports: [ "27017:27017" ]
        options: --name novels-mongo
      selenium:
        image: selenium/standalone-chrome:123.0
        ports: [ "4444:4444", "7900:7900" ]
        options: --name novels-selenium
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ env.PYTHON_VERSION }} }

      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f poetry.lock ]; then
            pip install poetry && poetry config virtualenvs.create false && poetry install -n
          else
            pip install -r requirements.txt
          fi
          pip install pytest

      - name: Apply minimal schema
        run: |
          sleep 8
          mysql -h 127.0.0.1 -uroot -p0000 novels < tests/data/seed/mysql/schema_and_seed_min.sql

      - name: Run integration tests
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: "3306"
          MYSQL_USER: root
          MYSQL_PASSWORD: 0000
          MYSQL_DB: novels
          MONGO_URI: mongodb://127.0.0.1:27017
          SELENIUM_REMOTE_URL: http://127.0.0.1:4444/wd/hub
        run: |
          pytest -q tests/integration --maxfail=1 --disable-warnings \
            --junitxml=tests/reports/pytest-integration.xml
      - name: Upload integration reports
        uses: actions/upload-artifact@v4
        with:
          name: integration-reports
          path: tests/reports/pytest-integration.xml

  e2e:
    runs-on: ubuntu-latest
    needs: [ integration ]
    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: 0000
          MYSQL_DATABASE: novels
        ports: [ "3306:3306" ]
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -proot || exit 1"
          --health-interval=10s --health-timeout=5s --health-retries=10
      mongo:
        image: mongo:7
        ports: [ "27017:27017" ]
      selenium:
        image: selenium/standalone-chrome:123.0
        ports: [ "4444:4444", "7900:7900" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: ${{ env.PYTHON_VERSION }} }
      - name: Install deps
        run: |
          python -m pip install -U pip
          if [ -f poetry.lock ]; then
            pip install poetry && poetry config virtualenvs.create false && poetry install -n
          else
            pip install -r requirements.txt
          fi
          pip install pytest uvicorn httpx
      - name: Apply minimal schema
        run: |
          sleep 8
          mysql -h 127.0.0.1 -uroot -p0000 novels < tests/data/seed/mysql/schema_and_seed_min.sql
      - name: Run E2E (TestClient / interval scheduler)
        env:
          SCHED_ENABLED: "true"
          SCHED_TZ: Asia/Seoul
          SCHED_PLATFORMS: KP
          SCHED_MAX_WORKERS: "2"
          SCHED_TEST_INTERVAL_SEC: "2"
          MYSQL_HOST: 127.0.0.1
          MYSQL_PORT: "3306"
          MYSQL_USER: root
          MYSQL_PASSWORD: 0000
          MYSQL_DB: novels
          MONGO_URI: mongodb://127.0.0.1:27017
          SELENIUM_REMOTE_URL: http://127.0.0.1:4444/wd/hub
        run: |
          pytest -q tests/e2e --maxfail=1 --disable-warnings \
            --junitxml=tests/reports/pytest-e2e.xml
      - name: Upload e2e reports
        uses: actions/upload-artifact@v4
        with:
          name: e2e-reports
          path: tests/reports/pytest-e2e.xml

  postman:
    runs-on: ubuntu-latest
    needs: [ e2e ]
    services:
      api:
        image: ghcr.io/OWNER/novel-api:dev  # 또는 로컬 빌드된 이미지 사용
        ports: [ "8000:8000" ]
        options: >-
          --health-cmd="wget -qO- http://127.0.0.1:8000/health || exit 1"
          --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v4
      - name: Install newman
        run: npm i -g newman newman-reporter-htmlextra
      - name: Newman run
        run: |
          newman run tests/postman/collections/novel-aggregator.postman_collection.json \
            -e tests/postman/environments/local.postman_environment.json \
            --reporters cli,junit,htmlextra \
            --reporter-junit-export tests/postman/reports/newman-results.xml \
            --reporter-htmlextra-export tests/postman/reports/newman-report.html
      - name: Upload postman reports
        uses: actions/upload-artifact@v4
        with:
          name: postman-reports
          path: tests/postman/reports/

  build:
    runs-on: ubuntu-latest
    needs: [ postman ]
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/novel-api:${{ github.sha }}
          context: .
          file: ./Dockerfile
      - name: Trivy scan (image)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/${{ github.repository }}/novel-api:${{ github.sha }}
          format: 'table'
          exit-code: '0'   # 난이도에 따라 '1'로 강제 실패도 가능
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
